site_name: matrixlayout
docs_dir: docs
site_dir: site
theme:
  name: readthedocs
plugins:
  - search
  - mkdocs-jupyter
nav:
  - Home: index.md
  - Overview: overview.md
  - Getting Started: getting-started.md
  - Specs: specs.md
  - Recipes: recipes.md
  - Rendering: rendering.md
  - Pitfalls: pitfalls.md
  - Interop: interop.md
  - End-to-End: end-to-end.md
  - Glossary: glossary.md
  - API: api.md
  - Notebooks:
      - Overview: notebooks/README.md
      - GE grids: notebooks/01_ge_grids.ipynb
      - QR grids: notebooks/02_qr_grids.ipynb
      - Eigen/SVD tables: notebooks/03_eig_svd_tables.ipynb
      - Backsubstitution: notebooks/04_backsubstitution.ipynb
      - Formatting and selectors: notebooks/05_formatting_selectors.ipynb
      - Rendering templates: notebooks/06_rendering_templates.ipynb
